/* Html5Oyunlar 2016 */
Html5Oyunlar({name:"wdg_footer",waiton:"html5oyunlar.loaded"},"Cache DOMEvent SWPUtils SWP Html5oyunlarZendesk DOMSelect".split(" "),function(g,e,m,h,a,d){function f(b,c,d){var a=(c-b.scrollTop)/d*2;setTimeout(function(){b.scrollTop+=a;f(b,c,d-2)},10)}h.init("footer");g.getItem({key:"Tracker.visitorId"},function(b){var c=d.get("#zendesk");if(null!==c){var f=d.get("#wdg_footer_zendesk_application_id"),e=d.get("#wdg_footer_zendesk_application_title"),k=d.get("#wdg_footer_zendesk_username"),l=d.get("#wdg_footer_zendesk_locale");
a.init(c,f.value,e.value,k.value,l.value,b);a.create()}});e.add("#switch_view","click",function(b){e.preventDefault(b);b=new Date;b.setTime(b.getTime()+31536E7);b="; expires="+b.toGMTString();var c=d.get("#switch_view").value;document.cookie="swp_view="+c+b+"; path=/";location.reload()});e.add("#scroll-to-top","click",function(b){f(document.body,0,50)})});Html5Oyunlar("html5oyunlar.import",{fullName:"Html5oyunlarZendesk",deps:["SWP","SWPEvent","Net","DOMSelect","JSLib"],module:function(g,e,m,h,a){var d,f,b,c="",n=a.get("html5oyunlar.module.portal.siteid"),p=a.get("html5oyunlar.module.portal.channelid"),k="",l="",q=encodeURIComponent(window.top.location.href);return{init:function(c,a,e,g,h,m){if("object"!==typeof c)return!1;d=c;f=a;b=e;k=g;l=h;return!0},create:function(){var a=[];c=l.substr(0,2);"pt"===c&amp;&amp;(c="pt-br");"object"==typeof d&amp;&amp;(a.push("site_id="+n),a.push("ChannelID="+
p),a.push("username="+k),a.push("gameid="+f),a.push("gametitle="+b),a.push("total=0"),a.push("url="+q),d.target="_blank",d.href="http://html5oyunlar.blogspot.com/hc/"+c+"?"+a.join("&amp;"))}}}});
/* Html5Oyunlar 2016 */
Html5Oyunlar(["SWP","DOMEvent"],function(a,b){a.init("favourite_menu");b.add(".pw-register-trigger","click",function(c){b.preventDefault(c);a.System.emit("popup.register.open")})});
/* Html5Oyunlar 2016 */
Html5Oyunlar("SWP Utils DOMSelect Cache DOMEvent BeLazy Cookie Net ThumbnailTracker".split(" "),function(d,e,l,g,u,m,v,w,x){d.init("recent_played_games_menu");var p=window.document,n=p.getElementById("wdg_recent_played_games_menu"),b=d.getProperty("*"),y=b.global_user_id,z=b.siteid,A=d.get("html5oyunlar.module.spapi.backend"),h="recent.played.games."+b.global_user_id,k=function(a,c){g.getItem("backend"===a?h:"recent.played.games",function(a){c(e.isArray(a)?a:[])})},q=function(a,c){g.setItem({key:"backend"===
a?h:"recent.played.games",value:c.slice(0,b.games_limit_client_storage),expires:15552E3})},B=function(a){g.getItem(h+".synced",function(c){a(e.isBoolean(c)?c:!1)})},r=function(a){g.setItem({key:h+".synced",value:!0===a,expires:2592E3})},C=function(a){var c=[];a.forEach(function(a){c.push({id:a,date:0})});a={url:A+"v1/recently-played/"+z+"/"+y,type:"POST",dataType:"json",data:JSON.stringify({items:c.slice(0,b.games_limit_authenticated)}),headers:{"x-auth-token":v.getItem("token")}};w.send(a,function(a){a.isError?
r(!1):r(!0)})},D=function(){var a=p.getElementById("authentication-incentive");a&&u.add(a,"click",function(){d.System.emit("popup.register.open")});d.getProperty("no_recent_games")?d.System.emit("recent.played.empty"):(d.System.emit("recent.played.filled"),window.setTimeout(m.trigger,500));m.handleImagesIn(n);x.track(n)},t=function(a,c,b){var f=a[0];f?k(f,function(E){a.shift();c[f]=E;t(a,c,b)}):b(c)};l=function(){if(!0!==b.track_only){var a=["client"];"backend"===b.storage_endpoint&&(a[1]="backend");
t(a,{},function(a){d.Widget.refresh({app_list:JSON.stringify(a),ui_format:b.ui_format,xhr:!0,lazyload_images:b.lazyload_images,lazyload_from_item:b.lazyload_from_item},{callback:D})})}};var F=e.once(l);k("client",function(a){var c=a.map(function(a){if(e.isObject(a)&&a.gid)return a.gid}).filter(function(a){return e.isString(a)}),d=a.filter(function(a){return e.isString(a)});a=a.length-c.length-d.length;var f;if(0<c.length||0<a)f=e.combine(d,c),q("client",f),"backend"===b.storage_endpoint&&k("backend",
function(a){0===a.length&&(a=f,q("backend",a))})});(function(a){"backend"===a&&B(function(a){a||k("backend",function(a){a=a.map(function(a){e.isObject(a)&&a.gid&&(a=a.gid);return a}).filter(function(a){return e.isString(a)});0<a.length&&C(a)})})})(b.storage_endpoint);e.isEmpty(b.wait_on_js_event)&&l();m.until("visible",n,function(){d.System.emit("recent.played.visible")});d.System.init(function(a){switch(a.name){case "inlinegame.open":case b.wait_on_js_event:F()}})});
/* Html5Oyunlar 2016 */
Html5Oyunlar({waiton:"html5oyunlar.loaded"},"SWPUtils SWP SWPEvent DOMSelect DOMEvent Placeholder".split(" "),function(f,b,q,l,c,k){b.init("popup_login");l.get("#popup-login-username")&&(k.init("popup-login-username"),k.init("popup-login-password"));var m=!1,g=0,r=document.createElement("div"),a=function(a){return document.getElementById(a)||r},h=function(e,b){var d=a("popup-login-error-generic"),c=a("popup-login-error-banned");e?"banned"==b?f.addClass(c,"visible"):f.addClass(d,"visible"):(f.removeClass(d,
"visible"),f.removeClass(c,"visible"))},d=function(e,t){g!==e&&2!==g&&(l.get("#popup-login-close")?(g=e,h(!1),a("popup-login-username").value="",a("popup-login-password").value="",a("popup-login-remember").checked=!0,1===e?(b.System.emit("gi.game.hide"),b.System.emit("popup.header.open"),f.removeClass(a("wdg_popup_login"),"hidden"),u(),/Trident/g.test(window.navigator.userAgent)||(document.getElementById("popup-login-username_ph")?c.trigger("#popup-login-username_ph","keydown"):a("popup-login-username").focus())):
(t||(b.System.emit("gi.game.show"),b.System.emit("popup.header.close")),b.System.emit("popup.closed",{type:"login"}),f.addClass(a("wdg_popup_login"),"hidden"))):(g=2,b.Widget.refresh({show_popup_contents:!0},{callback:function(){setTimeout(function(){k.init("popup-login-username");k.init("popup-login-password");g=0;d(1)},0)}})))},u=function(){!0!==m&&(m=!0,c.add(a("popup-login-form"),"submit",function(a){c.preventDefault(a);v()}),c.add(a("popup-login-close"),"click",function(){d(0)}),c.add(a("popup-login-facebook"),
"click",function(){n("facebook")}),c.add(a("popup-login-google"),"click",function(){n("google")}),c.add(a("popup-login-register"),"click",function(){d(0);b.System.emit("popup.register.open",{})}))},p=function(e){a("popup-login-button").enabled=e;f[e?"removeClass":"addClass"](a("popup-login-button"),"processing")},v=function(){if("undefined"===typeof a("popup-login-button").enabled||a("popup-login-button").enabled)h(!1),""===a("popup-login-password").value||""===a("popup-login-username").value?h(!0):
(b.System.emit("auth.login.request",{rememberMe:a("popup-login-remember").checked,username:a("popup-login-username").value,password:a("popup-login-password").value,callback:function(a){a.isError&&(a.scope&&a.scope.data&&"banned"==a.scope.data.string?h(!0,"banned"):h(!0),p(!0))}}),p(!1))},n=function(e){var c=a("popup-login-remember").checked;b.System.emit("auth.login.remember",{rememberMe:c});d(0);b.System.emit("popup.oauth.open",{provider:e})};"onload"===b.getProperty("requires_auth")&&q.listen("onDisplayGame",
function(){d(1)});b.System.init(function(a){switch(a.name){case "popup.login.open":0===g?d(1):d(0);break;case "popup.register.open":d(0,!0)}},!0)});
/* Html5Oyunlar 2016 */
Html5Oyunlar(["SWP","SWPUtils","DOMEvent","JSLib"],function(c,f,e,m){var d=document.getElementById("wdg_user_status"),g=document.getElementById("logged-user-avatar"),a=d.querySelector(".unit-counter"),h=!1,k=function(){h=!0;a&&m("api.notification.count",function(b){b.count?(a.innerHTML=b.count,f.removeClass(a,"is-hidden")):f.addClass(a,"is-hidden")})},l=function(){h||k()};c.init("user_status");e.add(d,"click",function(b){for(var a=b.target;!a.id;)a=a.parentNode;switch(a.id){case "login-button-nav":c.System.emit("popup.login.open",
{});b.preventDefault();break;case "logout-button-nav":c.System.emit("auth.logout.request",{}),b.preventDefault()}});a&&(e.add(d,"click",l),e.add(d,"mouseover",l));c.System.init(function(a){switch(a.name){case "avatar.update.current":g&&(g.src=a.body.avatarUrl);break;case "system.notification.update.amount":k()}})});